"""Initial Migration

Revision ID: 2de0ac44e004
Revises: 
Create Date: 2022-05-18 15:28:10.588235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de0ac44e004'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_type', sa.String(length=255), nullable=True),
    sa.Column('property_name', sa.String(length=255), nullable=True),
    sa.Column('property_location', sa.String(length=255), nullable=True),
    sa.Column('property_value', sa.Integer(), nullable=True),
    sa.Column('property_rooms', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_table('properties')
    # ### end Alembic commands ###
